### ISSUE TITLE
Add `url` or `docs` to validators

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/configuration-validator#14]
It would be really handy if instead of this:

```
entry: Expected string, array of strings, or an object, but got false
```

We got:

```
entry: Expected string, array of strings, or an object, but got false (see http://webpack.github.io/docs/configuration.html#entry)
```

Sure we could do this manually in each validator's message, but I think it'd be easier to do:

``` javascript
export default {
  key: 'entry',
  validate: validateEntry,
  docs: 'http://webpack.github.io/docs/configuration.html#entry',
}
```

Thoughts? :thought_balloon:

**Comment by sarbbottam** [comment]
Could we generate the `url`; `http://webpack.github.io/docs/configuration.html#${key}`, if the sections are identified by the exact `key` name at `http://webpack.github.io/docs/configuration.html`

**Comment by kentcdodds** [comment]
Hmmm... I'd prefer for it to be a little more straightforward. And it could be that sometimes the more helpful documentation page is different from that standard configuration key. Plus this core lib should avoid implementation details.

**Comment by kentcdodds** [comment]
And by that I mean that it should be unaware of the webpack-specific implementation

**Comment by sarbbottam** [comment]
> > Plus this core lib should avoid implementation details.
> > And by that I mean that it should be unaware of the webpack-specific implementation

My bad, I confused it with [webpack-validator](https://github.com/kentcdodds/webpack-validator)

I wanted to say, if possible it would be better to avoid the repetition of `http://webpack.github.io/docs/configuration.html` in [webpack-validator](https://github.com/kentcdodds/webpack-validator), who will be passing the `config`.

**Comment by kentcdodds** [comment]
We could easily write a helper for abstracting that :+1:
