### ISSUE TITLE
API Change

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/configuration-validator#15]
Originally from [this comment](https://github.com/kentcdodds/configuration-validator/pull/8#issuecomment-197947269)

I'm thinking about doing things a little differently... How about instead of this package doing any logging at all it simply returns the following info:

``` javascript
{
  errors: [], // array of errors
  warnings: [], // array of warnings
  errorsMessage: '', // the formatted error messages
  warningsMessage: '', // the formatted warning messages
  uncoveredFields: [], // the uncovered fields
  uncoveredFieldsMessage: '', // the formatted uncovered fields warning messages
}
```

This would require a bit of a refactor. But I think this would give you everything you're looking for. Then the consuming library can log the message however they like or not log it at all.

**Comment by kentcdodds** [comment]
Oh, and I think @nyrosmith wanted to tackle this one, but I think anyone can chime in and say they'd like to take it.

**Comment by nyrosmith** [comment]
> I think @nyrosmith wanted to tackle this one
> That's true, but if if someone else has more spare time ATM -> just do it
> As soon as I would start I'd come back and see if someone else already grabbed it.

**Comment by kentcdodds** [comment]
Make sure that you comment in here once you start working on it so people know #

**Comment by jonathanglasmeyer** [comment]
I'll take a stab at this, got some spare time today. :)
