### ISSUE TITLE
Fix error/warning spacing issues

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/configuration-validator#5]
Sometimes there are extra newlines between warnings and errors. Not sure why. Needs investigation.

**Comment by sarbbottam** [comment]
If you happen to reproduce it again, could you paste the screenshot for reference? Thanks!

**Comment by nyrosmith** [comment]
I thik we can close this issue as the API will change as discussed on https://github.com/kentcdodds/configuration-validator/pull/8

**Comment by kentcdodds** [comment]
Agreed
