### ISSUE TITLE
npm run check-coverage not working on Windows

### ISSUE THREAD

**Issue by nyrosmith** [kentcdodds/configuration-validator#9]
This command always fails with `ERROR: no coverage files found`.
I found [this nyc issue](https://github.com/bcoe/nyc/issues/190) but there they only talk about Node v5.8.0 and NPM v3.7.3
My setup = Node v5.9.0 and NPM v3.8.1

**Comment by kentcdodds** [comment]
I'm sure you are, but just to be sure, make sure that you first run `npm run cover` and that you get the text output indicating that there was coverage recorded. Then check your filesystem and you should see a `coverage/` folder with stuff in there..

**Comment by nyrosmith** [comment]
I should have mentioned that I ran `npm run cover` before. It is not working at all. Hopefully I'll find a solution soon

**Comment by sarbbottam** [comment]
replacing 
`"cover": "nyc --reporter=lcov --reporter=text --reporter=html npm run test",`
with
`"cover": "nyc --reporter=lcov --reporter=text --reporter=html ava \"src/**/*.test.js\" --require babel-register --coverage",`

solves the issue for me.

Happy to raise a PR for the same.

![nyc-coverage](https://cloud.githubusercontent.com/assets/949380/13860476/bec9f16c-ec45-11e5-8ea0-2e11ca71567a.gif)

**Comment by kentcdodds** [comment]
That's odd, but cool. Could you please make a PR and I'd like @nyrosmith to try it out.

**Comment by sarbbottam** [comment]
Sure would do that.
